# Generated by Django 5.0.2 on 2025-07-28 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directconversation',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat')], default='direct', max_length=10),
        ),
        migrations.AddField(
            model_name='directconversation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directconversation',
            name='group_name',
            field=models.CharField(blank=True, help_text='Name for group chats (required for group type)', max_length=100, null=True),
        ),
    ]
