# Generated by Django 5.0.2 on 2025-07-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_directconversation_conversation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directconversation',
            name='group_photo',
            field=models.ImageField(blank=True, help_text='Group photo for group chats', null=True, upload_to='connections/group_photos/'),
        ),
    ]
