# Generated by Django 4.2.27 on 2026-02-12 22:41

from django.db import migrations, models


def convert_maybe_to_no(apps, schema_editor):
    """
    Convert all 'maybe' RSVPs to 'no' since we're removing the 'maybe' option.
    This is a conservative approach - users who were unsure are marked as not attending.
    """
    EventRSVP = apps.get_model('events', 'EventRSVP')
    maybe_rsvps = EventRSVP.objects.filter(status='maybe')
    count = maybe_rsvps.count()
    
    if count > 0:
        maybe_rsvps.update(status='no')
        print(f"Converted {count} 'maybe' RSVPs to 'no'")


def reverse_conversion(apps, schema_editor):
    """
    Reverse migration - this is not perfect as we can't know which 'no' RSVPs
    were originally 'maybe', but we provide this for completeness.
    """
    # We can't reliably reverse this, so we just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_visibility'),
    ]

    operations = [
        migrations.RunPython(convert_maybe_to_no, reverse_conversion),
        migrations.AlterField(
            model_name='eventrsvp',
            name='status',
            field=models.CharField(
                max_length=5,
                choices=[('yes', 'Attending'), ('no', 'Not Attending')]
            ),
        ),
    ]
