# Generated by Django 5.0.2 on 2025-06-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_hash_signature_jobposting_search_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance & Accounting'), ('healthcare', 'Healthcare & Medical'), ('education', 'Education & Training'), ('sales_marketing', 'Sales & Marketing'), ('hospitality', 'Hospitality & Tourism'), ('manufacturing', 'Manufacturing & Production'), ('administrative', 'Administrative & Clerical'), ('construction', 'Construction & Engineering'), ('creative', 'Creative & Design'), ('other', 'Other')], default='other', help_text='Job industry category', max_length=50),
        ),
    ]
