# Generated by Django 5.0.2 on 2025-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_category'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobposting',
            name='jobs_jobpos_externa_2a3141_idx',
        ),
        migrations.AlterUniqueTogether(
            name='jobposting',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=50),
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='hash_signature',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='last_scraped',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='search_location',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='search_query',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='title_normalized',
        ),
    ]
