# Generated by Django 5.0.2 on 2025-07-22 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobposting_jobs_jobpos_externa_2a3141_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(help_text='The keyword used for scraping', max_length=200)),
                ('search_location', models.CharField(help_text='The location used for scraping', max_length=200)),
                ('source', models.CharField(choices=[('BOSSJOB', 'BossJob.ph'), ('JOBSTREET', 'JobStreet'), ('LINKEDIN', 'LinkedIn'), ('OTHER', 'Other')], default='BOSSJOB', max_length=20)),
                ('scraped_data', models.JSONField(help_text='Complete scraped job data as JSON')),
                ('total_found', models.IntegerField(default=0, help_text='Total number of jobs found in scraping')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['search_keyword'], name='jobs_scrape_search__e7bcab_idx'), models.Index(fields=['search_location'], name='jobs_scrape_search__1f457d_idx'), models.Index(fields=['source'], name='jobs_scrape_source_a0eda1_idx'), models.Index(fields=['scraped_at'], name='jobs_scrape_scraped_141fa2_idx')],
            },
        ),
    ]
