# Generated by Django 5.0.2 on 2025-10-16 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_scrapedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='audience',
            field=models.CharField(choices=[('PUBLIC', 'Public – anyone can view and apply'), ('ALUMNI_ONLY', 'Exclusive (Alumni Only) – only registered alumni users can apply')], default='PUBLIC', help_text='Who can view and apply for this job', max_length=20),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['audience'], name='jobs_jobpos_audienc_75e7e2_idx'),
        ),
    ]
