# Generated by Django 5.0.2 on 2025-10-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobposting_audience_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobposting',
            name='jobs_jobpos_audienc_75e7e2_idx',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='audience',
        ),
    ]
