# Generated by Django 4.2.27 on 2026-04-14 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_remove_jobposting_jobs_jobpos_audienc_75e7e2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_configured', models.BooleanField(default=False, help_text='Whether user has completed preference setup')),
                ('was_prompted', models.BooleanField(default=False, help_text='Whether user was shown the modal')),
                ('job_types', models.JSONField(blank=True, default=list, help_text='Selected job types (FULL_TIME, PART_TIME, etc.)')),
                ('location_text', models.CharField(blank=True, help_text='Comma-separated preferred locations', max_length=500)),
                ('remote_only', models.BooleanField(default=False, help_text='Only show remote jobs')),
                ('willing_to_relocate', models.BooleanField(default=False, help_text='Willing to relocate for opportunities')),
                ('minimum_salary', models.IntegerField(blank=True, help_text='Minimum acceptable salary in PHP', null=True)),
                ('source_type', models.CharField(choices=[('INTERNAL', 'NORSU Internal'), ('EXTERNAL', 'External'), ('BOTH', 'Both')], default='BOTH', help_text='Job source preference', max_length=20)),
                ('industries', models.JSONField(blank=True, default=list, help_text='Preferred industries/categories')),
                ('experience_levels', models.JSONField(blank=True, default=list, help_text='Preferred experience levels')),
                ('skill_matching_enabled', models.BooleanField(default=False, help_text='Enable skill-based filtering')),
                ('skill_match_threshold', models.IntegerField(default=50, help_text='Minimum skill match percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_configured_at', models.DateTimeField(blank=True, help_text='Timestamp when preferences were first configured', null=True)),
                ('modification_count', models.IntegerField(default=0, help_text='Number of times preferences have been modified')),
                ('user', models.OneToOneField(help_text='User who owns these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Preference',
                'verbose_name_plural': 'Job Preferences',
                'indexes': [models.Index(fields=['is_configured'], name='jobs_jobpre_is_conf_780301_idx'), models.Index(fields=['updated_at'], name='jobs_jobpre_updated_093383_idx')],
            },
        ),
    ]
