# Generated by Django 4.2.27 on 2026-04-14 22:46

from django.db import migrations


def create_job_preferences_for_existing_users(apps, schema_editor):
    """
    Create JobPreference records for all existing users who don't have one.
    This ensures backward compatibility when adding the JobPreference feature.
    """
    User = apps.get_model('auth', 'User')
    JobPreference = apps.get_model('jobs', 'JobPreference')
    
    # Get all users who don't have job preferences
    users_without_preferences = User.objects.filter(job_preferences__isnull=True)
    
    # Create JobPreference records in bulk
    preferences_to_create = [
        JobPreference(
            user=user,
            is_configured=False,
            was_prompted=False,
            job_types=[],
            location_text='',
            remote_only=False,
            willing_to_relocate=False,
            minimum_salary=None,
            source_type='BOTH',
            industries=[],
            experience_levels=[],
            skill_matching_enabled=False,
            skill_match_threshold=50,
            modification_count=0
        )
        for user in users_without_preferences
    ]
    
    # Bulk create for performance
    JobPreference.objects.bulk_create(preferences_to_create, ignore_conflicts=True)
    
    created_count = len(preferences_to_create)
    if created_count > 0:
        print(f"Created {created_count} JobPreference records for existing users")


def reverse_migration(apps, schema_editor):
    """
    Reverse operation: Delete all unconfigured JobPreference records.
    This only removes preferences that were auto-created and never configured by users.
    """
    JobPreference = apps.get_model('jobs', 'JobPreference')
    
    # Only delete preferences that were never configured
    deleted_count, _ = JobPreference.objects.filter(is_configured=False).delete()
    
    if deleted_count > 0:
        print(f"Deleted {deleted_count} unconfigured JobPreference records")


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_add_job_preference_model'),
    ]

    operations = [
        migrations.RunPython(
            create_job_preferences_for_existing_users,
            reverse_code=reverse_migration
        ),
    ]
