# Generated by Django 4.2.27 on 2026-04-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_populate_job_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedjob',
            name='source',
            field=models.CharField(choices=[('BOSSJOB', 'BossJob.ph'), ('JOBSTREET', 'JobStreet Philippines'), ('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed Philippines'), ('KALIBRR', 'Kalibrr'), ('PHILJOBNET', 'PhilJobNet (DOLE)'), ('ONLINEJOBS', 'OnlineJobs.ph'), ('JORA', 'Jora Philippines'), ('MYNIMO', 'Mynimo'), ('WORKABROAD', 'WorkAbroad.ph'), ('OTHER', 'Other')], default='BOSSJOB', max_length=20),
        ),
    ]
