# Generated by Django 4.2.27 on 2026-04-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_ph_job_site_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('bossjob', 'BossJob.ph'), ('jobstreet', 'JobStreet Philippines'), ('indeed', 'Indeed Philippines'), ('linkedin', 'LinkedIn'), ('kalibrr', 'Kalibrr'), ('philjobnet', 'PhilJobNet (DOLE)'), ('onlinejobs', 'OnlineJobs.ph'), ('jora', 'Jora Philippines'), ('mynimo', 'Mynimo'), ('workabroad', 'WorkAbroad.ph'), ('other', 'Other')], default='manual', max_length=50),
        ),
    ]
