# Generated by Django 5.0.2 on 2026-04-19 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0011_add_scraper_source_choices_to_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserJobAIScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, help_text='AI match score (0-100)', null=True)),
                ('reason', models.TextField(blank=True)),
                ('strengths_json', models.JSONField(blank=True, default=list)),
                ('gaps_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('profile_version', models.BigIntegerField(default=0)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ai_scores', to='jobs.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_ai_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Job AI Score',
                'verbose_name_plural': 'User Job AI Scores',
                'unique_together': {('user', 'job')},
                'indexes': [
                    models.Index(fields=['user', 'status']),
                    models.Index(fields=['user', 'score']),
                    models.Index(fields=['computed_at']),
                ],
            },
        ),
    ]
