# Generated by Django 4.2.19 on 2025-02-19 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('profile_update', 'Profile Update'), ('group_join', 'Group Join'), ('group_post', 'Group Post'), ('event_rsvp', 'Event RSVP'), ('feedback', 'Feedback Submission'), ('document_upload', 'Document Upload')], max_length=20)),
                ('points', models.PositiveIntegerField(default=1, help_text='Points earned for this activity')),
                ('description', models.TextField(blank=True, help_text='Optional description of the engagement activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Engagement',
                'verbose_name_plural': 'User Engagements',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EngagementScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Total engagement points earned')),
                ('level', models.PositiveIntegerField(default=1, help_text='User engagement level')),
                ('last_activity', models.DateTimeField(blank=True, help_text='Timestamp of last engagement activity', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engagement Score',
                'verbose_name_plural': 'Engagement Scores',
                'ordering': ['-total_points'],
            },
        ),
    ]
