# Generated by Django 5.0.2 on 2025-07-31 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_announcements', models.BooleanField(default=True)),
                ('email_events', models.BooleanField(default=True)),
                ('email_surveys', models.BooleanField(default=True)),
                ('email_job_postings', models.BooleanField(default=True)),
                ('email_connections', models.BooleanField(default=True)),
                ('email_mentorship', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('app_announcements', models.BooleanField(default=True)),
                ('app_events', models.BooleanField(default=True)),
                ('app_surveys', models.BooleanField(default=True)),
                ('app_job_postings', models.BooleanField(default=True)),
                ('app_connections', models.BooleanField(default=True)),
                ('app_mentorship', models.BooleanField(default=True)),
                ('app_messages', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('announcement', 'New Announcement'), ('event', 'New Event'), ('survey', 'New Survey'), ('job_posting', 'New Job Posting'), ('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('mentorship_request', 'Mentorship Request'), ('mentorship_approved', 'Mentorship Approved'), ('mentorship_rejected', 'Mentorship Rejected'), ('new_message', 'New Message'), ('system', 'System Notification')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_alumni_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='core_notifi_recipie_4d7e73_idx'), models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'), models.Index(fields=['notification_type', '-created_at'], name='core_notifi_notific_38b6f7_idx')],
            },
        ),
    ]
