# Generated by Django 5.0.2 on 2025-08-07 10:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationpreference_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title', max_length=200)),
                ('section_type', models.CharField(choices=[('UNIVERSITY_HISTORY', 'University History'), ('MISSION_VISION', 'Mission & Vision'), ('STATISTICS', 'Alumni Statistics'), ('ACHIEVEMENTS', 'Notable Achievements'), ('LEADERSHIP', 'Leadership Team'), ('GENERAL', 'General Information')], max_length=20, unique=True)),
                ('content', ckeditor.fields.RichTextField(help_text='Section content with rich text formatting')),
                ('image', models.ImageField(blank=True, help_text='Optional section image', null=True, upload_to='about_us/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('MAIN_OFFICE', 'Main University Office'), ('ALUMNI_OFFICE', 'Alumni Affairs Office'), ('ADMISSIONS', 'Admissions Office'), ('REGISTRAR', 'Registrar Office'), ('STUDENT_AFFAIRS', 'Student Affairs'), ('EMERGENCY', 'Emergency Contact')], max_length=20, unique=True)),
                ('office_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_primary', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('office_hours', models.TextField(blank=True, help_text='Office hours information')),
                ('additional_info', models.TextField(blank=True, help_text='Additional contact information')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['order', 'office_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('YOUTUBE', 'YouTube'), ('WEBSITE', 'Official Website'), ('OTHER', 'Other')], max_length=20)),
                ('platform_name', models.CharField(blank=True, help_text="Custom platform name if 'Other' is selected", max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(default='fas fa-link', help_text='Font Awesome icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('position_type', models.CharField(choices=[('PRESIDENT', 'University President'), ('VP_ACADEMIC', 'Vice President for Academic Affairs'), ('VP_ADMIN', 'Vice President for Administration'), ('DEAN', 'Dean'), ('DIRECTOR', 'Director'), ('ALUMNI_COORDINATOR', 'Alumni Coordinator'), ('STAFF', 'Staff Member')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Brief biography or description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within position type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['position_type', 'order', 'name'],
            },
        ),
    ]
