# Generated by Django 5.0.2 on 2025-09-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutussection_contactinformation_socialmedialink_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsSection',
        ),
        migrations.DeleteModel(
            name='ContactInformation',
        ),
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
