# Generated by Django 4.2.7 on 2025-10-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pagesection_siteconfiguration_staffmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('services', 'Services Page')], default='home', max_length=20),
        ),
    ]
