# Generated by Django 5.0.2 on 2025-10-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pagesection_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Gmail', 'Outlook', 'Custom')", max_length=100)),
                ('host', models.CharField(help_text='SMTP server host (e.g., smtp.gmail.com)', max_length=255)),
                ('port', models.PositiveIntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL, 25 for non-encrypted)')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption (recommended for port 587)')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption (for port 465)')),
                ('username', models.EmailField(help_text='SMTP username (usually your email address)', max_length=254)),
                ('password', models.CharField(help_text='SMTP password or app password', max_length=255)),
                ('from_email', models.EmailField(help_text="Default 'from' email address", max_length=254)),
                ('from_name', models.CharField(blank=True, help_text="Default 'from' name (optional)", max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Use this configuration for sending emails')),
                ('is_verified', models.BooleanField(default=False, help_text='Configuration has been tested and verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.TextField(blank=True, help_text='Result of the last test')),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
