# Generated by Django 5.0.2 on 2025-10-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_smtpconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReCaptchaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for this reCAPTCHA configuration', max_length=100)),
                ('site_key', models.CharField(help_text='Your reCAPTCHA site key from Google reCAPTCHA console', max_length=200)),
                ('secret_key', models.CharField(help_text='Your reCAPTCHA secret key from Google reCAPTCHA console', max_length=200)),
                ('version', models.CharField(choices=[('v2', 'reCAPTCHA v2'), ('v3', 'reCAPTCHA v3')], default='v3', help_text='reCAPTCHA version to use', max_length=10)),
                ('threshold', models.FloatField(default=0.5, help_text='Score threshold for reCAPTCHA v3 (0.0 to 1.0, where 1.0 is very likely a good interaction)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'reCAPTCHA Configuration',
                'verbose_name_plural': 'reCAPTCHA Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
