# Generated by Django 5.0.2 on 2025-10-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recaptchaconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='recaptchaconfig',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether reCAPTCHA functionality is enabled (turn off to disable all reCAPTCHA)'),
        ),
    ]
