# Generated by Django 5.0.2 on 2025-10-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_recaptchaconfig_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaptchaconfig',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Whether reCAPTCHA functionality is enabled (turn off to disable all reCAPTCHA)'),
        ),
    ]
