# Generated by Django 5.0.2 on 2025-10-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_recaptchaconfig_enabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageSection',
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
        migrations.DeleteModel(
            name='StaffMember',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
