# Generated by Django 5.0.2 on 2025-10-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_pagesection_delete_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrevoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Brevo Production', 'Brevo Sandbox')", max_length=100)),
                ('api_key', models.CharField(help_text='Brevo API key from your account settings', max_length=255)),
                ('api_url', models.URLField(default='https://api.brevo.com/v3/smtp/email', help_text='Brevo API endpoint URL')),
                ('from_email', models.EmailField(help_text="Default 'from' email address (must be verified in Brevo)", max_length=254)),
                ('from_name', models.CharField(blank=True, help_text="Default 'from' name (optional)", max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Use this configuration for sending emails')),
                ('is_verified', models.BooleanField(default=False, help_text='Configuration has been tested and verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.TextField(blank=True, help_text='Result of the last test')),
            ],
            options={
                'verbose_name': 'Brevo Configuration',
                'verbose_name_plural': 'Brevo Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('smtp', 'SMTP'), ('brevo', 'Brevo API')], default='smtp', help_text='Email provider to use for sending emails', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Use this provider for sending emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('emails_sent', models.PositiveIntegerField(default=0, help_text='Number of emails sent using this provider')),
                ('last_error', models.TextField(blank=True, help_text='Last error message (if any)')),
            ],
            options={
                'verbose_name': 'Email Provider',
                'verbose_name_plural': 'Email Providers',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
