# Generated by Django 5.0.2 on 2025-11-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_brevoconfig_emailprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'New Announcement'), ('event', 'New Event'), ('survey', 'New Survey'), ('job_posting', 'New Job Posting'), ('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('mentorship_request', 'Mentorship Request'), ('mentorship_approved', 'Mentorship Approved'), ('mentorship_rejected', 'Mentorship Rejected'), ('mentorship_disabled', 'Mentorship Disabled'), ('mentorship_reactivation_approved', 'Mentorship Reactivation Approved'), ('mentorship_reactivation_rejected', 'Mentorship Reactivation Rejected'), ('new_message', 'New Message'), ('system', 'System Notification')], max_length=35),
        ),
    ]
