# Generated by Django 4.2.27 on 2026-01-06 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_increase_notification_type_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('old_status', models.BooleanField(help_text='Previous is_active value', verbose_name='Old Status')),
                ('new_status', models.BooleanField(help_text='New is_active value', verbose_name='New Status')),
                ('reason', models.TextField(help_text='Explanation for the status change', verbose_name='Reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Status Change',
                'verbose_name_plural': 'User Status Changes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_userst_user_id_d62f30_idx'), models.Index(fields=['changed_by', '-timestamp'], name='core_userst_changed_6fd479_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'User Created'), ('UPDATE', 'User Updated'), ('ROLE_ASSIGN', 'Role Assigned'), ('ROLE_REMOVE', 'Role Removed'), ('STATUS_ENABLE', 'User Enabled'), ('STATUS_DISABLE', 'User Disabled'), ('PASSWORD_RESET', 'Password Reset'), ('BULK_ACTION', 'Bulk Action')], max_length=20, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('details', models.JSONField(default=dict, help_text='Stores action-specific data in JSON format', verbose_name='Details')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_management_actions_performed', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_management_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Audit Log',
                'verbose_name_plural': 'User Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_userau_user_id_e53bc6_idx'), models.Index(fields=['action', '-timestamp'], name='core_userau_action_23bd21_idx'), models.Index(fields=['performed_by', '-timestamp'], name='core_userau_perform_6e75b3_idx')],
            },
        ),
    ]
