# Generated by Django 4.2.27 on 2026-01-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userstatuschange_userauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization name', max_length=255)),
                ('logo', models.URLField(help_text='URL to organization logo')),
                ('url', models.URLField(help_text='Organization website URL')),
                ('telephone', models.CharField(help_text='Contact telephone number', max_length=50)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('street_address', models.CharField(help_text='Street address', max_length=255)),
                ('address_locality', models.CharField(help_text='City or locality', max_length=100)),
                ('address_region', models.CharField(help_text='State, province, or region', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal or ZIP code', max_length=20)),
                ('address_country', models.CharField(help_text="Country code (ISO 3166-1 alpha-2, e.g., 'PH')", max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this organization schema is active')),
            ],
            options={
                'verbose_name': 'Organization Schema',
                'verbose_name_plural': 'Organization Schemas',
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(help_text="URL path of the page (e.g., '/' or '/about-us/')", max_length=255, unique=True)),
                ('meta_title', models.CharField(help_text='Page title for search results (50-60 characters recommended)', max_length=60)),
                ('meta_description', models.CharField(help_text='Page description for search results (150-160 characters recommended)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (1200x630 pixels recommended)', null=True, upload_to='seo/og_images/')),
                ('twitter_image', models.ImageField(blank=True, help_text='Twitter Card image (800x418 pixels recommended)', null=True, upload_to='seo/twitter_images/')),
                ('canonical_url', models.URLField(blank=True, help_text='Preferred URL for this page (leave blank to use page_path)')),
                ('sitemap_priority', models.DecimalField(decimal_places=1, default=0.5, help_text='Priority in sitemap (0.0 to 1.0)', max_digits=2)),
                ('sitemap_changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', help_text='How frequently the page changes', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this SEO configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
                'ordering': ['page_path'],
            },
        ),
    ]
