# Generated by Django 4.2.27 on 2026-02-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organizationschema_pageseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name for this SSO configuration (e.g., 'Google Production')", max_length=100)),
                ('provider', models.CharField(choices=[('google', 'Google OAuth'), ('facebook', 'Facebook OAuth')], help_text='SSO provider type', max_length=20)),
                ('client_id', models.CharField(help_text='OAuth Client ID from provider console', max_length=500)),
                ('secret_key', models.CharField(help_text='OAuth Client Secret from provider console', max_length=500)),
                ('scopes', models.TextField(default='profile,email', help_text="Comma-separated list of OAuth scopes (e.g., 'profile,email')")),
                ('verified_email', models.BooleanField(default=True, help_text='Trust email verification from this provider')),
                ('is_active', models.BooleanField(default=False, help_text='Use this configuration for authentication')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable this SSO provider')),
                ('is_verified', models.BooleanField(default=False, help_text='Configuration has been tested and verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.TextField(blank=True, help_text='Result of the last configuration test')),
                ('login_count', models.PositiveIntegerField(default=0, help_text='Number of successful logins using this configuration')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SSO Configuration',
                'verbose_name_plural': 'SSO Configurations',
                'ordering': ['-is_active', 'provider', '-created_at'],
                'unique_together': {('provider', 'is_active')},
            },
        ),
    ]
