# Generated by Django 4.2.27 on 2026-02-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_sso_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoconfig',
            name='provider',
            field=models.CharField(choices=[('google', 'Google OAuth')], help_text='SSO provider type', max_length=20),
        ),
    ]
