# Generated by Django 4.2.27 on 2026-02-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_ssoconfig_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaptchaconfig',
            name='version',
            field=models.CharField(choices=[('v2_checkbox', 'reCAPTCHA v2 Checkbox'), ('v2_invisible', 'reCAPTCHA v2 Invisible'), ('v2', 'reCAPTCHA v2 (Legacy)'), ('v3', 'reCAPTCHA v3')], default='v2_invisible', help_text='reCAPTCHA version to use', max_length=20),
        ),
    ]
