# Generated by Django 4.2.27 on 2026-02-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_update_recaptcha_version_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaptchaconfig',
            name='version',
            field=models.CharField(choices=[('v2', 'reCAPTCHA v2'), ('v3', 'reCAPTCHA v3')], default='v3', help_text='reCAPTCHA version to use', max_length=10),
        ),
    ]
