# Generated by Django 4.2.27 on 2026-04-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_recaptchaconfig_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name for this configuration (e.g., 'Gemini Production')", max_length=100)),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI')], default='gemini', help_text='AI provider', max_length=20)),
                ('api_key', models.CharField(help_text='API key from the provider console', max_length=500)),
                ('model_name', models.CharField(default='gemini-2.0-flash', help_text='Model to use (e.g., gemini-2.0-flash, gpt-4o-mini)', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Use this configuration for AI features')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable AI features globally')),
                ('is_verified', models.BooleanField(default=False, help_text='Configuration has been tested and verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.TextField(blank=True, help_text='Result of the last test')),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
