# Generated by Django 5.0.2 on 2026-04-19 22:40

import core.models.system_settings
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_add_ai_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, public pages are replaced with the maintenance page.",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="The site is under maintenance. Please try again later.",
                        help_text="Message shown to visitors when maintenance mode is enabled.",
                    ),
                ),
                (
                    "runtime_debug",
                    models.BooleanField(
                        default=core.models.system_settings.default_runtime_debug,
                        help_text="App-level runtime debug flag (does not change Django settings.DEBUG).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_system_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
