# Generated by Django 5.0.2 on 2025-02-12 22:44

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('country', django_countries.fields.CountryField(default='PH', max_length=2)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('college', models.CharField(choices=[('CAS', 'College of Arts and Sciences'), ('CAFF', 'College of Agriculture, Forestry and Fishery'), ('CBA', 'College of Business Administration'), ('CCJE', 'College of Criminal Justice Education'), ('CEA', 'College of Engineering and Architecture'), ('CIT', 'College of Industrial Technology'), ('CNPAHS', 'College of Nursing, Pharmacy and Allied Health Sciences'), ('CTE', 'College of Teacher Education'), ('CTHM', 'College of Tourism and Hospitality Management')], max_length=10)),
                ('campus', models.CharField(choices=[('MAIN', 'Main Campus I & II (Dumaguete)'), ('BAIS', 'Bais Campus I & II'), ('GUI', 'Guihulngan Campus'), ('MAB', 'Mabinay Campus'), ('BSC', 'Bayawan-Sta. Catalina Campus'), ('SIA', 'Siaton Campus'), ('PAM', 'Pamplona Campus')], max_length=10)),
                ('graduation_year', models.IntegerField()),
                ('course', models.CharField(max_length=200)),
                ('major', models.CharField(blank=True, max_length=200)),
                ('honors', models.CharField(blank=True, max_length=200)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('employment_status', models.CharField(choices=[('EMPLOYED_FULL', 'Employed Full-Time'), ('EMPLOYED_PART', 'Employed Part-Time'), ('SELF_EMPLOYED', 'Self-Employed'), ('UNEMPLOYED', 'Unemployed'), ('STUDENT', 'Further Studies'), ('RETIRED', 'Retired'), ('INTERN', 'Internship/OJT')], default='UNEMPLOYED', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('interests', models.TextField(blank=True, help_text='Comma-separated list of interests')),
                ('bio', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alumni',
                'ordering': ['-graduation_year', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='AlumniDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume/CV'), ('CERT', 'Certification'), ('DIPLOMA', 'Diploma'), ('TOR', 'Transcript of Records'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='alumni_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='alumni_directory.alumni')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['graduation_year', 'course'], name='alumni_dire_graduat_d32c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['province', 'city'], name='alumni_dire_provinc_1f8edb_idx'),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['college', 'campus'], name='alumni_dire_college_b08d1c_idx'),
        ),
    ]
