# Generated by Django 5.0.2 on 2025-05-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_directory', '0001_initial'),
        ('accounts', '0003_sync_experience_data'),  # Ensure data migration is applied before removing
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerPath',
        ),
    ]
