# Generated by Django 4.2.27 on 2026-03-24 12:27

from django.db import migrations, models


def verify_existing_documents(apps, schema_editor):
    """Set all existing documents to verified"""
    AlumniDocument = apps.get_model('alumni_directory', 'AlumniDocument')
    AlumniDocument.objects.filter(is_verified=False).update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_directory', '0002_add_college_of_law'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidocument',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(verify_existing_documents, migrations.RunPython.noop),
    ]
