# Generated by Django 4.2.27 on 2026-03-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_directory', '0003_auto_verify_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='college',
            field=models.CharField(choices=[('CAS', 'College of Arts and Sciences'), ('CAF', 'College of Agriculture and Forestry'), ('CAFF', 'College of Agriculture, Forestry and Fishery'), ('CBA', 'College of Business Administration'), ('CCJE', 'College of Criminal Justice Education'), ('CEA', 'College of Engineering and Architecture'), ('CIT', 'College of Industrial Technology'), ('COL', 'College of Law'), ('CNPAHS', 'College of Nursing, Pharmacy and Allied Health Sciences'), ('CTE', 'College of Teacher Education'), ('CTHM', 'College of Tourism and Hospitality Management')], max_length=10),
        ),
    ]
