# Generated by Django 4.2.27 on 2026-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_directory', '0005_update_colleges_and_programs'),
    ]

    operations = [
    ]
