# Generated by Django 5.0.2 on 2025-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('university_name', models.CharField(default='Negros Oriental State University', help_text='Full name of the university', max_length=200)),
                ('university_short_name', models.CharField(default='NORSU', help_text='Short name or acronym', max_length=50)),
                ('university_description', models.TextField(default='Negros Oriental State University (NORSU) is a premier state university in the Philippines, committed to providing quality education and fostering excellence in research, extension, and production services.', help_text='Main description of the university')),
                ('university_extended_description', models.TextField(default='Established in 2004 through the merger of several educational institutions, NORSU has grown to become a leading center of learning in the Visayas region. Our university is dedicated to developing competent professionals who contribute to national development and global competitiveness.', help_text='Extended description of the university')),
                ('establishment_year', models.CharField(default='2004', help_text='Year the university was established', max_length=10)),
                ('mission', models.TextField(default='To provide quality and relevant education through instruction, research, extension, and production services for the holistic development of individuals and communities towards a progressive society.', help_text='University mission statement')),
                ('vision', models.TextField(default='A premier state university in the Asia-Pacific region recognized for excellence in instruction, research, extension, and production that produces globally competitive graduates and empowered communities.', help_text='University vision statement')),
                ('about_page_title', models.CharField(default='About NORSU Alumni Network', help_text='Title for the About page', max_length=200)),
                ('about_page_subtitle', models.TextField(default='Learn more about our university, mission, and the people behind our alumni community', help_text='Subtitle for the About page')),
            ],
            options={
                'verbose_name': 'About Page Configuration',
                'verbose_name_plural': 'About Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='AlumniStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('statistic_type', models.CharField(choices=[('alumni_members', 'Alumni Members'), ('alumni_groups', 'Alumni Groups'), ('annual_events', 'Annual Events'), ('job_opportunities', 'Job Opportunities'), ('mentors', 'Mentors'), ('scholarships', 'Scholarships'), ('countries', 'Countries Represented'), ('industries', 'Industries Represented')], help_text='Type of statistic', max_length=30, unique=True)),
                ('value', models.CharField(help_text="Statistic value (e.g., '5,000+', '25+')", max_length=20)),
                ('label', models.CharField(help_text='Display label for the statistic', max_length=100)),
                ('icon', models.CharField(default='fas fa-users', help_text='Font Awesome icon class', max_length=50)),
                ('icon_color', models.CharField(default='primary', help_text='Bootstrap color class for the icon', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this statistic should be displayed')),
            ],
            options={
                'verbose_name': 'Alumni Statistic',
                'verbose_name_plural': 'Alumni Statistics',
                'ordering': ['order', 'statistic_type'],
            },
        ),
    ]
