# Generated by Django 5.0.2 on 2025-10-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_aboutpageconfig_alumnistatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('office_name', models.CharField(default='Negros Oriental State University', help_text='Office/University name', max_length=200)),
                ('address_line1', models.CharField(default='Kagawasan, Ave. Rizal', help_text='Address line 1', max_length=200)),
                ('address_line2', models.CharField(default='Dumaguete City, 6200', help_text='Address line 2', max_length=200)),
                ('address_line3', models.CharField(default='Negros Oriental, Philippines', help_text='Address line 3', max_length=200)),
                ('primary_phone', models.CharField(default='+63 35 422 6002', help_text='Primary phone number', max_length=20)),
                ('secondary_phone', models.CharField(blank=True, default='+63 35 225 2376', help_text='Secondary phone number', max_length=20)),
                ('primary_email', models.EmailField(default='alumni@norsu.edu.ph', help_text='Primary email address', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, default='info@norsu.edu.ph', help_text='Secondary email address', max_length=254)),
                ('weekday_hours', models.CharField(default='Monday - Friday: 8:00 AM - 5:00 PM', help_text='Weekday office hours', max_length=100)),
                ('saturday_hours', models.CharField(default='Saturday: 8:00 AM – 12:00 PM', help_text='Saturday office hours', max_length=100)),
                ('sunday_hours', models.CharField(default='Sunday: Closed', help_text='Sunday office hours', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Configuration',
                'verbose_name_plural': 'Contact Configuration',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('telegram', 'Telegram')], help_text='Social media platform', max_length=20, unique=True)),
                ('url', models.URLField(help_text='Social media profile URL')),
                ('icon_class', models.CharField(default='fab fa-facebook', help_text='Font Awesome icon class', max_length=50)),
                ('color_class', models.CharField(default='primary', help_text='Bootstrap color class for the icon', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this social media link should be displayed')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
