# Generated by Django 5.0.2 on 2025-10-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_contactconfig_socialmedialink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactConfig',
        ),
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
    ]
