# Generated by Django 5.0.2 on 2025-10-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_delete_contactconfig_delete_socialmedialink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnistatistic',
            name='statistic_type',
            field=models.CharField(choices=[('alumni_members', 'Alumni Members'), ('alumni_groups', 'Alumni Groups'), ('annual_events', 'Annual Events'), ('job_opportunities', 'Job Opportunities'), ('mentors', 'Mentors'), ('scholarships', 'Scholarships'), ('countries', 'Countries Represented'), ('industries', 'Industries Represented')], help_text='Type of statistic', max_length=30),
        ),
    ]
