# Generated by Django 5.0.2 on 2025-10-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_unique_constraint_from_statistic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnistatistic',
            name='icon_color',
            field=models.CharField(default='#007bff', help_text='Hex color code for the icon (e.g., #007bff)', max_length=7),
        ),
    ]
