# Generated by Django 5.0.2 on 2025-10-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_update_icon_color_to_hex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticPage',
        ),
    ]
