# Generated by Django 4.2.27 on 2026-02-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_remove_static_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('title', models.CharField(help_text='Link text to display', max_length=100)),
                ('url', models.CharField(help_text="URL or Django URL name (e.g., 'core:home' or '/about/')", max_length=500)),
                ('section', models.CharField(choices=[('quick_links', 'Quick Links'), ('information', 'Information'), ('legal', 'Legal'), ('resources', 'Resources')], default='information', help_text='Which footer section this link belongs to', max_length=20)),
                ('icon', models.CharField(default='fas fa-link', help_text="Font Awesome icon class (e.g., 'fas fa-home')", max_length=50)),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in a new browser tab')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within section (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link should be displayed')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['section', 'order', 'title'],
                'indexes': [models.Index(fields=['section', 'is_active', 'order'], name='cms_footerl_section_3d1350_idx')],
            },
        ),
    ]
