# Generated by Django 4.2.27 on 2026-02-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NORSUCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('name', models.CharField(help_text="Campus name (e.g., 'Main Campus', 'Bais Campus')", max_length=200)),
                ('location', models.CharField(help_text='Campus location/address', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the campus')),
                ('image', models.ImageField(help_text='Campus photo for slider', upload_to='cms/campuses/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in slider (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this campus should be displayed in slider')),
            ],
            options={
                'verbose_name': 'NORSU Campus',
                'verbose_name_plural': 'NORSU Campuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NORSUVMGOHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('vision', models.TextField(default='A globally recognized state university.', help_text='NORSU Vision statement')),
                ('mission', models.TextField(default='Negros Oriental State University delivers global excellence through advanced instruction, impactful research, and sustainable extension, with strategic partnerships and modern infrastructure shaping effective leaders to serve the Philippine society and the world.', help_text='NORSU Mission statement')),
                ('goals', models.TextField(default='ASPIRE:\n• Achieve global recognition by program excellence\n• Strengthen research through impactful innovation\n• Promote enhanced community extension services\n• Integrate partnerships and international relations\n• Revitalize infrastructure with operational systems\n• Enrich student life and leadership opportunities', help_text='NORSU Strategic Goals (use bullet points or line breaks)')),
                ('core_values', models.TextField(default='SHINE:\n• Spirituality\n• Honesty\n• Innovation\n• Nurturance\n• Excellence', help_text='NORSU Core Values')),
                ('quality_policy', models.TextField(default='Negros Oriental State University commits to delivering quality instruction, research, extension and production. We ensure compliance with all statutory and regulatory requirements and continuously work to improve our management system to meet our quality objectives.', help_text='NORSU Quality Policy')),
                ('history_brief', models.TextField(default='Negros Oriental State University was established in 1907, when Governor Hermenegildo Villanueva proposed the establishment of industrial arts education in Negros Oriental Provincial School (NOPS), the precursor of the Negros Oriental High School (NOHS).', help_text='Brief history summary')),
                ('history_full', models.TextField(default='The beginnings of Negros Oriental State University date back to 1907, from a single woodworking class at what was then the Negros Oriental Provincial School. On December 3, 1927, by virtue of Act No. 3377 of the Philippine Legislature, the woodworking class became the Negros Oriental Trade School (NOTS). By virtue of Republic Act No. 1579 signed into law on June 16, 1956, NOTS became the East Visayan School of Arts and Trades (EVSAT). Through Batas Pambansa No. 401 signed by President Ferdinand E. Marcos on June 10, 1983, the Central Visayas Polytechnic College (CVPC) came into being. Finally, through Republic Act No. 9299 signed by President Gloria Macapagal Arroyo on June 25, 2004, CVPC was converted into Negros Oriental State University (NORSU).', help_text='Full detailed history')),
                ('establishment_year', models.CharField(default='1907', help_text='Year NORSU was originally established', max_length=10)),
                ('university_status_year', models.CharField(default='2004', help_text='Year it became a university', max_length=10)),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Display VMGO section on homepage')),
                ('show_history_on_homepage', models.BooleanField(default=True, help_text='Display history section on homepage')),
            ],
            options={
                'verbose_name': 'NORSU VMGO & History',
                'verbose_name_plural': 'NORSU VMGO & History',
            },
        ),
        migrations.CreateModel(
            name='NORSUOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('name', models.CharField(help_text="Full name with title (e.g., 'Dr. John Doe')", max_length=200)),
                ('position', models.CharField(help_text='Official position/title', max_length=200)),
                ('position_level', models.IntegerField(choices=[(1, 'University President'), (2, 'Vice President'), (3, 'Dean'), (4, 'Associate Dean'), (5, 'Director'), (6, 'Department Head'), (7, 'Other Official')], default=7, help_text='Position level for hierarchical ordering')),
                ('department', models.CharField(blank=True, help_text='Department, college, or office', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Brief biography or description')),
                ('image', models.ImageField(blank=True, help_text='Official photo', null=True, upload_to='cms/officials/')),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within position level (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this official should be displayed')),
            ],
            options={
                'verbose_name': 'NORSU Official',
                'verbose_name_plural': 'NORSU Officials',
                'ordering': ['position_level', 'order', 'name'],
                'indexes': [models.Index(fields=['position_level', 'is_active', 'order'], name='cms_norsuof_positio_519377_idx')],
            },
        ),
    ]
