# Generated by Django 4.2.27 on 2026-02-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_norsucampus_norsuvmgohistory_norsuofficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_alumni_count',
            field=models.CharField(default='5,000+', help_text="Number of alumni (e.g., '5,000+')", max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_countries_count',
            field=models.CharField(default='30+', help_text="Number of countries represented (e.g., '30+')", max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_headline',
            field=models.CharField(default='Advance Your Career With 5,000+ NORSU Professionals', help_text='Main headline for the hero section (6-10 words recommended)', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_microcopy',
            field=models.CharField(default='Takes 2 minutes • No credit card required', help_text='Microcopy text below CTA buttons to reduce friction', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_opportunities_count',
            field=models.CharField(default='500+', help_text="Number of career opportunities (e.g., '500+')", max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_primary_cta_text',
            field=models.CharField(default='Start Your Career Growth', help_text='Primary CTA button text (2-4 words)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_secondary_cta_text',
            field=models.CharField(default='Sign In', help_text='Secondary CTA button text (2-3 words)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subheadline',
            field=models.TextField(default='Access exclusive job opportunities, industry mentorship, and a network of alumni leaders across 30+ countries.', help_text='Subheadline for the hero section (15-25 words recommended)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_variant',
            field=models.CharField(default='variation-1', help_text="Current hero section variant for A/B testing (e.g., 'variation-1', 'variation-2')", max_length=50),
        ),
    ]
