# Generated by Django 4.2.27 on 2026-02-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_siteconfig_hero_alumni_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Background image for the hero section (recommended: 1920x600px or larger)', null=True, upload_to='cms/hero_backgrounds/'),
        ),
    ]
