# Generated by Django 4.2.27 on 2026-02-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_add_hero_background_image'),
    ]

    operations = [
    ]
