# Generated by Django 4.2.27 on 2026-02-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_set_default_hero_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Background image for the hero section (recommended: 1920x600px, < 500KB)', null=True, upload_to='cms/hero/'),
        ),
    ]
