# Generated by Django 4.2.27 on 2026-02-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_add_hero_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='about_content',
            field=models.TextField(default='Negros Oriental State University (NORSU) is a premier state university in the Philippines, committed to providing quality education and fostering excellence in research, extension, and production services.', help_text='Introduction text about NORSU (200-300 words recommended)'),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='about_title',
            field=models.CharField(default='About NORSU', help_text='Title for About section', max_length=100),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='goals_title',
            field=models.CharField(default='Goals', help_text='Title for Goals section', max_length=100),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show/hide this section on homepage'),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='mission_title',
            field=models.CharField(default='NORSU Mission', help_text='Title for Mission section', max_length=100),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='section_title',
            field=models.CharField(default='NORSU Vision, Mission, Goals & Core Values', help_text='Main section title', max_length=200),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='values_title',
            field=models.CharField(default='Core Values', help_text='Title for Core Values section', max_length=100),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='vision_title',
            field=models.CharField(default='NORSU Vision', help_text='Title for Vision section', max_length=100),
        ),
        migrations.AlterField(
            model_name='norsuvmgohistory',
            name='core_values',
            field=models.TextField(default='SHINE:\n• Spirituality\n• Honesty\n• Innovation\n• Nurturance\n• Excellence', help_text='NORSU Core Values (supports bullet points)'),
        ),
        migrations.AlterField(
            model_name='norsuvmgohistory',
            name='goals',
            field=models.TextField(default='ASPIRE:\n• Achieve global recognition by program excellence\n• Strengthen research through impactful innovation\n• Promote enhanced community extension services\n• Integrate partnerships and international relations\n• Revitalize infrastructure with operational systems\n• Enrich student life and leadership opportunities', help_text='NORSU Strategic Goals (supports bullet points)'),
        ),
        migrations.AlterField(
            model_name='norsuvmgohistory',
            name='mission',
            field=models.TextField(default='Negros Oriental State University delivers global excellence through advanced instruction, impactful research, and sustainable extension, with strategic partnerships and modern infrastructure shaping effective leaders to serve the Philippine society and the world.', help_text='NORSU Mission statement (100-150 words recommended)'),
        ),
        migrations.AlterField(
            model_name='norsuvmgohistory',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Display VMGO section on homepage (deprecated, use is_active)'),
        ),
        migrations.AlterField(
            model_name='norsuvmgohistory',
            name='vision',
            field=models.TextField(default='A globally recognized state university.', help_text='NORSU Vision statement (50-100 words recommended)'),
        ),
    ]
