# Generated by Django 4.2.27 on 2026-02-20 23:14

from django.db import migrations


def populate_vmgo_content(apps, schema_editor):
    """
    Populate default NORSU VMGO content.
    Creates a singleton instance with comprehensive NORSU information.
    """
    NORSUVMGOHistory = apps.get_model('cms', 'NORSUVMGOHistory')
    
    # Default content for NORSU VMGO section
    default_content = {
        'section_title': 'NORSU Vision, Mission, Goals & Core Values',
        'is_active': True,
        'about_title': 'About NORSU',
        'about_content': (
            'Negros Oriental State University (NORSU) is a premier state university in the Philippines, '
            'committed to providing quality education and fostering excellence in research, extension, '
            'and production services. Established in 1907, NORSU has grown from a single woodworking class '
            'to a comprehensive university serving thousands of students across multiple campuses. '
            'With a rich history spanning over a century, NORSU continues to shape future leaders and '
            'contribute to the development of Negros Oriental and the nation.'
        ),
        'vision_title': 'NORSU Vision',
        'vision': 'A globally recognized state university.',
        'mission_title': 'NORSU Mission',
        'mission': (
            'Negros Oriental State University delivers global excellence through advanced instruction, '
            'impactful research, and sustainable extension, with strategic partnerships and modern '
            'infrastructure shaping effective leaders to serve the Philippine society and the world.'
        ),
        'goals_title': 'Goals',
        'goals': (
            'ASPIRE:\n'
            '• Achieve global recognition by program excellence\n'
            '• Strengthen research through impactful innovation\n'
            '• Promote enhanced community extension services\n'
            '• Integrate partnerships and international relations\n'
            '• Revitalize infrastructure with operational systems\n'
            '• Enrich student life and leadership opportunities'
        ),
        'values_title': 'Core Values',
        'core_values': (
            'SHINE:\n'
            '• Spirituality\n'
            '• Honesty\n'
            '• Innovation\n'
            '• Nurturance\n'
            '• Excellence'
        ),
        'quality_policy': (
            'Negros Oriental State University commits to delivering quality instruction, research, '
            'extension and production. We ensure compliance with all statutory and regulatory requirements '
            'and continuously work to improve our management system to meet our quality objectives.'
        ),
        'history_brief': (
            'Negros Oriental State University was established in 1907, when Governor Hermenegildo Villanueva '
            'proposed the establishment of industrial arts education in Negros Oriental Provincial School (NOPS), '
            'the precursor of the Negros Oriental High School (NOHS).'
        ),
        'history_full': (
            'The beginnings of Negros Oriental State University date back to 1907, from a single woodworking '
            'class at what was then the Negros Oriental Provincial School. On December 3, 1927, by virtue of '
            'Act No. 3377 of the Philippine Legislature, the woodworking class became the Negros Oriental Trade '
            'School (NOTS). By virtue of Republic Act No. 1579 signed into law on June 16, 1956, NOTS became '
            'the East Visayan School of Arts and Trades (EVSAT). Through Batas Pambansa No. 401 signed by '
            'President Ferdinand E. Marcos on June 10, 1983, the Central Visayas Polytechnic College (CVPC) '
            'came into being. Finally, through Republic Act No. 9299 signed by President Gloria Macapagal '
            'Arroyo on June 25, 2004, CVPC was converted into Negros Oriental State University (NORSU).'
        ),
        'establishment_year': '1907',
        'university_status_year': '2004',
        'show_on_homepage': True,
        'show_history_on_homepage': True,
    }
    
    # Get or create the singleton instance
    vmgo_instance, created = NORSUVMGOHistory.objects.get_or_create(
        pk=1,
        defaults=default_content
    )
    
    # If instance already exists but has empty or default content, update it
    if not created:
        # Check if content needs updating (if it's still using minimal defaults)
        needs_update = False
        
        # Check if about_content is still the minimal default
        if len(vmgo_instance.about_content) < 200:
            needs_update = True
        
        # Update if needed
        if needs_update:
            for field, value in default_content.items():
                setattr(vmgo_instance, field, value)
            vmgo_instance.save()


def reverse_populate_vmgo_content(apps, schema_editor):
    """
    Reverse migration - optionally delete the created instance.
    Note: We don't delete by default to preserve any user modifications.
    """
    # Intentionally left empty to preserve data
    # If you want to delete the instance on reverse, uncomment below:
    # NORSUVMGOHistory = apps.get_model('cms', 'NORSUVMGOHistory')
    # NORSUVMGOHistory.objects.filter(pk=1).delete()
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_norsuvmgohistory_about_content_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_vmgo_content,
            reverse_populate_vmgo_content
        ),
    ]
