# Generated by Django 4.2.27 on 2026-02-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_update_vmgo_acronym_format'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPageConfig',
        ),
    ]
