# Generated by Django 4.2.27 on 2026-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_remove_about_page_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='quality_objective_1',
            field=models.TextField(default='Organize Alumni Research and Development to support the quality program based', help_text='First quality objective (O)'),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='quality_objective_2',
            field=models.TextField(default='Develop support and good will of the Alumni to institutional and program activities;', help_text='Second quality objective (D)'),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='quality_objective_3',
            field=models.TextField(default='Achieve professional network and partnership between Alumni communities; and', help_text='Third quality objective (A)'),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='quality_objective_4',
            field=models.TextField(default='Assure quality services for the Alumni; the Alumni community and the University.', help_text='Fourth quality objective (A)'),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='quality_objectives_footer',
            field=models.TextField(default='In compliance with the applicable regulatory requirements and continual improvement of its management System', help_text='Footer text for quality objectives section'),
        ),
        migrations.AddField(
            model_name='norsuvmgohistory',
            name='quality_objectives_title',
            field=models.CharField(default='Quality Objectives', help_text='Title for Quality Objectives section', max_length=100),
        ),
    ]
