# Generated by Django 5.0.2 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_add_quality_objectives_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this object was last modified.', verbose_name='Modified')),
                ('page_type', models.CharField(choices=[('terms', 'Terms of Use'), ('privacy', 'Privacy Notice'), ('community-guidelines', 'Community Guidelines'), ('data-privacy-request', 'Data Privacy Request')], max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Page content in Markdown. HTML is sanitized before display.')),
                ('effective_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
                'ordering': ['order', 'title'],
            },
        ),
    ]
