# Generated by Django 5.0.2 on 2025-07-02 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], default='NOT_STARTED', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_goals', to='accounts.mentorshiprequest')),
            ],
            options={
                'verbose_name': 'Mentorship Goal',
                'verbose_name_plural': 'Mentorship Goals',
                'ordering': ['priority', 'target_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meeting_date', models.DateTimeField()),
                ('duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('meeting_link', models.URLField(blank=True, help_text='Video call or meeting location link')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Meeting notes and action items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.mentorshiprequest')),
            ],
            options={
                'verbose_name': 'Mentorship Meeting',
                'verbose_name_plural': 'Mentorship Meetings',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='mentorship/messages/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.mentorshiprequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_mentorship_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentorship Message',
                'verbose_name_plural': 'Mentorship Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACHIEVED', 'Achieved')], default='PENDING', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='mentorship.mentorshipgoal')),
            ],
            options={
                'verbose_name': 'Mentorship Milestone',
                'verbose_name_plural': 'Mentorship Milestones',
                'ordering': ['target_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completed_items', models.TextField(blank=True, help_text='JSON list of completed items/milestones', null=True)),
                ('next_steps', models.TextField(blank=True, help_text='Next steps and goals', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_progress_updates', to=settings.AUTH_USER_MODEL)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='accounts.mentorshiprequest')),
            ],
            options={
                'verbose_name': 'Mentorship Progress',
                'verbose_name_plural': 'Mentorship Progress Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('initial_proficiency', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Master')], default=1)),
                ('current_proficiency', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Master')], default=1)),
                ('target_proficiency', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Master')], default=3)),
                ('notes', models.TextField(blank=True)),
                ('last_assessment_date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to='accounts.mentorshiprequest')),
            ],
            options={
                'verbose_name': 'Skill Progress',
                'verbose_name_plural': 'Skill Progress',
                'ordering': ['-current_proficiency', 'skill_name'],
                'unique_together': {('mentorship', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='TimelineMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text="Week/Day period (e.g., '1-2', '3-4')", max_length=50)),
                ('description', models.CharField(help_text='Description of the milestone', max_length=500)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_milestone_entries', to='accounts.mentorshiprequest')),
            ],
            options={
                'verbose_name': 'Timeline Milestone',
                'verbose_name_plural': 'Timeline Milestones',
                'ordering': ['period', 'created_at'],
                'unique_together': {('mentorship', 'period', 'description')},
            },
        ),
    ]
