# Generated by Django 4.2.19 on 2025-03-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipmeeting',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
    ]
