# Generated by Django 5.0.2 on 2025-07-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinemilestone',
            name='description',
            field=models.CharField(max_length=500, help_text="Description of the milestone"),
        ),
    ]
