# Generated by Django 5.0.2 on 2025-10-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False, help_text='Whether the initial setup has been completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the setup was completed', null=True)),
                ('setup_data', models.JSONField(blank=True, default=dict, help_text='Store setup configuration data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setup State',
                'verbose_name_plural': 'Setup States',
            },
        ),
    ]
