# Generated by Django 5.0.2 on 2025-10-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100)),
                ('backend', models.CharField(default='console', help_text='Email backend', max_length=50)),
                ('host', models.CharField(blank=True, help_text='SMTP host', max_length=255)),
                ('port', models.IntegerField(default=587, help_text='SMTP port')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS')),
                ('username', models.EmailField(blank=True, help_text='SMTP username', max_length=254)),
                ('password', models.CharField(blank=True, help_text='SMTP password', max_length=255)),
                ('from_email', models.EmailField(blank=True, help_text='Default from email', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature name', max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether the feature is enabled')),
                ('description', models.TextField(blank=True, help_text='Feature description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Toggle',
                'verbose_name_plural': 'Feature Toggles',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuration value')),
                ('description', models.TextField(blank=True, help_text='Description of this setting')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
    ]
