# Generated by Django 5.0.2 on 2025-10-17 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_emailconfiguration_featuretoggle_siteconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfiguration',
        ),
        migrations.DeleteModel(
            name='FeatureToggle',
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
