# Generated by Django 5.0.2 on 2025-02-12 22:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, help_text='Two-letter country code (ISO 3166-1 alpha-2)', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('linkedin_profile', models.URLField(blank=True, max_length=255)),
                ('facebook_profile', models.URLField(blank=True, max_length=255)),
                ('twitter_profile', models.URLField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_completed_registration', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, choices=[('BSIT', 'Bachelor of Science in Information Technology'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BSIS', 'Bachelor of Science in Information Systems'), ('BSA', 'Bachelor of Science in Accountancy'), ('BSBA', 'Bachelor of Science in Business Administration'), ('BEED', 'Bachelor of Elementary Education'), ('BSED', 'Bachelor of Secondary Education'), ('BSN', 'Bachelor of Science in Nursing'), ('BSCRIM', 'Bachelor of Science in Criminology'), ('BSHRM', 'Bachelor of Science in Hotel and Restaurant Management'), ('BSTM', 'Bachelor of Science in Tourism Management'), ('BSE', 'Bachelor of Science in Engineering'), ('BSP', 'Bachelor of Science in Psychology'), ('OTHER', 'Other Program')], max_length=10, null=True)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, choices=[('NORSU-G', 'NORSU Guihulngan'), ('NORSU-BC', 'NORSU Bais City'), ('NORSU-MB', 'NORSU Mabinay'), ('NORSU-SC', 'NORSU Siaton'), ('NORSU-PC', 'NORSU Pamplona'), ('NORSU-SCC', 'NORSU Sta. Catalina'), ('NORSU-VC', 'NORSU Valencia'), ('OTHER', 'Other Campus')], max_length=10, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('TRANSCRIPT', 'Academic Transcript'), ('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('RESUME', 'Resume/CV'), ('OTHER', 'Other')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('TECH', 'Technical'), ('SOFT', 'Soft Skills'), ('LANG', 'Language'), ('CERT', 'Certification'), ('OTHER', 'Other')], max_length=5)),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Elementary'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-proficiency_level'],
            },
        ),
    ]
