# Generated by Django 4.2.19 on 2025-02-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employer',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('0-15K', 'Below ₱15,000'), ('15-30K', '₱15,000 - ₱30,000'), ('30-50K', '₱30,000 - ₱50,000'), ('50-80K', '₱50,000 - ₱80,000'), ('80-100K', '₱80,000 - ₱100,000'), ('100K+', 'Above ₱100,000'), ('PREFER_NOT', 'Prefer not to say')], max_length=20),
        ),
    ]
