# Generated by Django 4.2.19 on 2025-02-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_employer_profile_current_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(choices=[('EMPLOYED_FULL', 'Employed Full-Time'), ('EMPLOYED_PART', 'Employed Part-Time'), ('SELF_EMPLOYED', 'Self-Employed'), ('UNEMPLOYED', 'Unemployed'), ('STUDENT', 'Further Studies'), ('RETIRED', 'Retired'), ('INTERN', 'Internship/OJT')], default='UNEMPLOYED', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('0-15K', 'Below ₱15,000'), ('15K-30K', '₱15,000 - ₱30,000'), ('30K-50K', '₱30,000 - ₱50,000'), ('50K-80K', '₱50,000 - ₱80,000'), ('80K-100K', '₱80,000 - ₱100,000'), ('100K+', 'Above ₱100,000'), ('PREFER_NOT', 'Prefer not to say')], default='PREFER_NOT', max_length=20),
        ),
    ]
