# Generated by Django 5.0.2 on 2025-10-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('0-15K', 'Below ₱15,000'), ('15K-30K', '₱15,000 - ₱30,000'), ('30K-50K', '₱30,000 - ₱50,000'), ('50K-80K', '₱50,000 - ₱80,000'), ('80K-100K', '₱80,000 - ₱100,000'), ('100K+', 'Above ₱100,000')], default='', max_length=20),
        ),
    ]
