# Generated by Django 5.0.2 on 2025-11-07 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_experience_salary_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='removal_reason',
            field=models.TextField(blank=True, help_text='Reason for removing this mentor', null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='removed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when mentor was removed', null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='removed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who removed this mentor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_mentors', to=settings.AUTH_USER_MODEL),
        ),
    ]
