# Generated by Django 5.0.2 on 2025-11-07 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_mentor_removal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorReactivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address used for verification', max_length=254)),
                ('verification_code', models.CharField(blank=True, help_text='OTP verification code', max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether email has been verified')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('request_reason', models.TextField(blank=True, help_text='Optional reason for requesting reactivation')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, help_text='Expiration time for verification code', null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivation_requests', to='accounts.mentor')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_reactivation_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reactivation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Reactivation Request',
                'verbose_name_plural': 'Mentor Reactivation Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
