# Generated by Django 4.2.27 on 2026-01-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_mentor_reactivation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hr',
            field=models.BooleanField(default=False, help_text='Designates whether this user has HR permissions for job management'),
        ),
    ]
