# Generated by Django 4.2.27 on 2026-03-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_is_alumni_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(blank=True, choices=[('NORSU-G', 'NORSU Guihulngan'), ('NORSU-BC', 'NORSU Bais City'), ('NORSU-MB', 'NORSU Mabinay'), ('NORSU-SC', 'NORSU Siaton'), ('NORSU-PC', 'NORSU Pamplona'), ('NORSU-BSC', 'NORSU Bayawan-Sta. Catalina'), ('NORSU-VC', 'NORSU Valencia'), ('OTHER', 'Other Campus')], max_length=10, null=True),
        ),
    ]
