# Generated by Django 4.2.27 on 2026-03-24 02:02

from django.db import migrations


def update_scc_to_bsc(apps, schema_editor):
    """Update all Education records with NORSU-SCC to NORSU-BSC"""
    Education = apps.get_model('accounts', 'Education')
    updated_count = Education.objects.filter(school='NORSU-SCC').update(school='NORSU-BSC')
    if updated_count > 0:
        print(f"Updated {updated_count} Education records from NORSU-SCC to NORSU-BSC")


def reverse_bsc_to_scc(apps, schema_editor):
    """Reverse migration: Update NORSU-BSC back to NORSU-SCC"""
    Education = apps.get_model('accounts', 'Education')
    updated_count = Education.objects.filter(school='NORSU-BSC').update(school='NORSU-SCC')
    if updated_count > 0:
        print(f"Reverted {updated_count} Education records from NORSU-BSC to NORSU-SCC")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_update_campus_code_scc_to_bsc'),
    ]

    operations = [
        migrations.RunPython(update_scc_to_bsc, reverse_bsc_to_scc),
    ]
