# Generated by Django 4.2.27 on 2026-03-24 12:28

from django.db import migrations, models


def verify_existing_documents(apps, schema_editor):
    """Set all existing documents to verified"""
    Document = apps.get_model('accounts', 'Document')
    Document.objects.filter(is_verified=False).update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_valencia_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(verify_existing_documents, migrations.RunPython.noop),
    ]
