# Generated by Django 5.0.2 on 2025-08-07 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GCashConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default GCash', max_length=100, verbose_name='Configuration Name')),
                ('gcash_number', models.CharField(max_length=15, verbose_name='GCash Number')),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('qr_code_image', models.ImageField(upload_to='gcash_qr/', verbose_name='QR Code Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for donors', verbose_name='Payment Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'GCash Configuration',
                'verbose_name_plural': 'GCash Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='gcash_transaction_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='GCash Transaction ID'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Payment Proof'),
        ),
        migrations.AddField(
            model_name='donation',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Date'),
        ),
        migrations.AddField(
            model_name='donation',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Verification Notes'),
        ),
        migrations.AddField(
            model_name='donation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donations', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], default='gcash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending_payment', max_length=20, verbose_name='Status'),
        ),
    ]
