# Generated by Django 5.0.2 on 2025-08-07 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_gcashconfig_donation_gcash_transaction_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('duplicate_image', 'Duplicate Payment Image'), ('suspicious_amount', 'Suspicious Amount Pattern'), ('rapid_donations', 'Rapid Multiple Donations'), ('unusual_location', 'Unusual Location'), ('blacklisted_user', 'Blacklisted User'), ('manual_review', 'Manual Review Required')], max_length=20, verbose_name='Alert Type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, verbose_name='Severity')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='pending', max_length=15, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='donations.donation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Fraud Alert',
                'verbose_name_plural': 'Fraud Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('email', 'Email Address'), ('ip', 'IP Address'), ('phone', 'Phone Number'), ('name', 'Name Pattern'), ('gcash_number', 'GCash Number')], max_length=15, verbose_name='Entity Type')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('reason', models.TextField(verbose_name='Reason for Blacklisting')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blacklists', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Blacklisted Entity',
                'verbose_name_plural': 'Blacklisted Entities',
                'ordering': ['-created_at'],
                'unique_together': {('entity_type', 'value')},
            },
        ),
    ]
