# Generated by Django 5.0.2 on 2025-08-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_fraudalert_blacklistedentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Reference Number'),
        ),
    ]
