# Generated by Django 5.0.2 on 2025-08-07 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_increase_reference_number_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcashconfig',
            options={'ordering': ['priority', '-is_active', 'name'], 'verbose_name': 'GCash Configuration', 'verbose_name_plural': 'GCash Configurations'},
        ),
        migrations.AddField(
            model_name='donation',
            name='gcash_account',
            field=models.ForeignKey(blank=True, help_text='The GCash account used for this donation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.gcashconfig', verbose_name='GCash Account Used'),
        ),
        migrations.AddField(
            model_name='gcashconfig',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description for this GCash account', max_length=200, verbose_name='Account Description'),
        ),
        migrations.AddField(
            model_name='gcashconfig',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Display order (1 = highest priority)', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='gcashconfig',
            name='account_name',
            field=models.CharField(help_text='Full name as registered in GCash', max_length=100, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='gcashconfig',
            name='gcash_number',
            field=models.CharField(help_text='11-digit Philippine mobile number (e.g., 09123456789)', max_length=15, verbose_name='GCash Number'),
        ),
        migrations.AlterField(
            model_name='gcashconfig',
            name='instructions',
            field=models.TextField(blank=True, help_text='Additional instructions for donors using this account', verbose_name='Payment Instructions'),
        ),
        migrations.AlterField(
            model_name='gcashconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this account is available for donations', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='gcashconfig',
            name='qr_code_image',
            field=models.ImageField(help_text='Upload QR code image for this GCash account', upload_to='gcash_qr_codes/', verbose_name='QR Code Image'),
        ),
        migrations.AlterUniqueTogether(
            name='gcashconfig',
            unique_together={('gcash_number',)},
        ),
    ]
