# Generated by Django 5.0.2 on 2025-08-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_enhance_gcash_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcashconfig',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'GCash Configuration', 'verbose_name_plural': 'GCash Configurations'},
        ),
        migrations.AlterUniqueTogether(
            name='gcashconfig',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='donation',
            name='gcash_account',
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash')], default='gcash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='gcashconfig',
            name='account_name',
            field=models.CharField(max_length=100, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='gcashconfig',
            name='gcash_number',
            field=models.CharField(max_length=15, verbose_name='GCash Number'),
        ),
        migrations.AlterField(
            model_name='gcashconfig',
            name='instructions',
            field=models.TextField(blank=True, help_text='Additional instructions for donors', verbose_name='Payment Instructions'),
        ),
        migrations.AlterField(
            model_name='gcashconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='gcashconfig',
            name='qr_code_image',
            field=models.ImageField(upload_to='gcash_qr/', verbose_name='QR Code Image'),
        ),
        migrations.RemoveField(
            model_name='gcashconfig',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gcashconfig',
            name='priority',
        ),
    ]
