# Generated by Django 5.0.2 on 2025-10-21 00:36

from django.db import migrations


def populate_campaign_types(apps, schema_editor):
    """Populate the database with default campaign types"""
    CampaignType = apps.get_model('donations', 'CampaignType')
    
    campaign_types = [
        {
            'name': 'Scholarship Fund',
            'slug': 'scholarship-fund',
            'description': 'Fundraising campaigns for student scholarships and financial aid'
        },
        {
            'name': 'Infrastructure Development',
            'slug': 'infrastructure-development',
            'description': 'Campaigns to improve university facilities and infrastructure'
        },
        {
            'name': 'Research & Innovation',
            'slug': 'research-innovation',
            'description': 'Funding for research projects and innovation initiatives'
        },
        {
            'name': 'Student Support',
            'slug': 'student-support',
            'description': 'Support for student activities, organizations, and programs'
        },
        {
            'name': 'Alumni Events',
            'slug': 'alumni-events',
            'description': 'Funding for alumni reunions, conferences, and networking events'
        },
        {
            'name': 'Emergency Relief',
            'slug': 'emergency-relief',
            'description': 'Emergency funds for students and alumni in need'
        },
        {
            'name': 'Technology Upgrade',
            'slug': 'technology-upgrade',
            'description': 'Modernizing university technology and equipment'
        },
        {
            'name': 'Community Outreach',
            'slug': 'community-outreach',
            'description': 'Programs that benefit the local community and society'
        }
    ]
    
    for ct_data in campaign_types:
        CampaignType.objects.get_or_create(
            slug=ct_data['slug'],
            defaults={
                'name': ct_data['name'],
                'description': ct_data['description']
            }
        )


def reverse_populate_campaign_types(apps, schema_editor):
    """Remove the default campaign types"""
    CampaignType = apps.get_model('donations', 'CampaignType')
    
    slugs_to_remove = [
        'scholarship-fund',
        'infrastructure-development',
        'research-innovation',
        'student-support',
        'alumni-events',
        'emergency-relief',
        'technology-upgrade',
        'community-outreach'
    ]
    
    CampaignType.objects.filter(slug__in=slugs_to_remove).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_alter_gcashconfig_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_campaign_types,
            reverse_populate_campaign_types
        ),
    ]
