# Generated by Django 5.0.2 on 2025-10-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_populate_campaign_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='visibility',
            field=models.CharField(choices=[('registered_alumni', 'Registered Alumni'), ('public', 'Public')], default='registered_alumni', max_length=20, verbose_name='Visibility'),
        ),
    ]
