# Generated by Django 5.0.2 on 2025-10-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_add_visibility_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='reference_number',
            field=models.CharField(help_text='Enter the reference number from your GCash receipt', max_length=30, unique=True, verbose_name='Reference Number'),
        ),
    ]
