# Generated by Django 5.0.2 on 2025-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_alter_donation_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='reference_number',
            field=models.CharField(help_text='Enter the reference number from your GCash receipt (alphanumeric and symbols allowed)', max_length=100, unique=True, verbose_name='Reference Number'),
        ),
    ]
