# Generated by Django 5.0.2 on 2025-10-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_make_reference_number_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Enter the reference number from your GCash receipt (alphanumeric and symbols allowed)', max_length=100, null=True, verbose_name='Reference Number'),
        ),
    ]
