# Generated by Django 5.0.2 on 2025-10-25 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_remove_reference_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='allow_donations',
            field=models.BooleanField(default=False, help_text='Enable donations for this campaign', verbose_name='Allow Donations'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gcash_config',
            field=models.ForeignKey(blank=True, help_text='Select which GCash account will receive donations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='donations.gcashconfig', verbose_name='GCash Configuration'),
        ),
    ]
