# Generated by Django 5.0.2 on 2025-11-05 04:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View')], max_length=10)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('app_label', models.CharField(db_index=True, max_length=50)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Previous field values (for updates)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New field values (for creates/updates)', null=True)),
                ('changed_fields', models.JSONField(blank=True, help_text='List of changed field names (for updates)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'action'], name='log_viewer__timesta_7d6a48_idx'), models.Index(fields=['model_name', 'app_label'], name='log_viewer__model_n_f4f79b_idx'), models.Index(fields=['user', 'timestamp'], name='log_viewer__user_id_f8bdec_idx')],
            },
        ),
    ]
