# Generated by Django 5.0.2 on 2025-11-12 02:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveStorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_storage_gb', models.DecimalField(decimal_places=2, default=10.0, help_text='Maximum storage size for archives in GB', max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('warning_threshold_percent', models.IntegerField(default=80, help_text='Percentage at which to show warning (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('critical_threshold_percent', models.IntegerField(default=95, help_text='Percentage at which to pause archival (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('current_size_gb', models.DecimalField(decimal_places=2, default=0.0, help_text='Current archive storage size in GB', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_size_check', models.DateTimeField(blank=True, help_text='When storage size was last calculated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Archive Storage Configuration',
                'verbose_name_plural': 'Archive Storage Configuration',
            },
        ),
        migrations.CreateModel(
            name='LogCleanupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Whether automatic cleanup is enabled')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='How often to run cleanup', max_length=10)),
                ('execution_time', models.TimeField(help_text='Time of day to run cleanup (24-hour format)')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For weekly frequency - which day to run', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='For monthly frequency - which day to run (1-28)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('last_run', models.DateTimeField(blank=True, help_text='When cleanup was last executed', null=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='When cleanup is scheduled to run next', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Cleanup Schedule',
                'verbose_name_plural': 'Log Cleanup Schedules',
            },
        ),
        migrations.CreateModel(
            name='LogRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('audit', 'Audit Logs'), ('file', 'File Logs')], help_text='Type of logs this policy applies to', max_length=10, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Whether this retention policy is active')),
                ('retention_days', models.PositiveIntegerField(help_text='Number of days to retain logs before deletion (1-3650)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('export_before_delete', models.BooleanField(default=True, help_text='Export logs to archive before deletion')),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('both', 'Both CSV and PDF')], default='csv', help_text='Format for exported archive files', max_length=10)),
                ('archive_path', models.CharField(default='logs/archives', help_text='Path relative to MEDIA_ROOT for storing archives', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Retention Policy',
                'verbose_name_plural': 'Log Retention Policies',
                'ordering': ['log_type'],
            },
        ),
        migrations.CreateModel(
            name='LogOperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('scheduled', 'Scheduled Cleanup'), ('manual', 'Manual Cleanup')], help_text='Whether this was a scheduled or manual operation', max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], help_text='Overall status of the operation', max_length=10)),
                ('started_at', models.DateTimeField(help_text='When the operation started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the operation completed', null=True)),
                ('audit_logs_processed', models.IntegerField(default=0, help_text='Number of audit log records processed')),
                ('audit_logs_deleted', models.IntegerField(default=0, help_text='Number of audit log records deleted')),
                ('file_logs_processed', models.IntegerField(default=0, help_text='Number of file log entries processed')),
                ('file_logs_deleted', models.IntegerField(default=0, help_text='Number of file log entries deleted')),
                ('archives_created', models.IntegerField(default=0, help_text='Number of archive files created')),
                ('error_message', models.TextField(blank=True, help_text='Error details if operation failed')),
                ('archive_files', models.JSONField(default=list, help_text='List of created archive files')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered manual operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Operation History',
                'verbose_name_plural': 'Log Operation History',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='log_viewer__started_6696c9_idx'), models.Index(fields=['status', '-started_at'], name='log_viewer__status_f11816_idx')],
            },
        ),
    ]
