# Generated by Django 5.0.2 on 2025-11-12 03:04

from django.db import migrations


def create_default_configurations(apps, schema_editor):
    """
    Create default LogRetentionPolicy instances and ArchiveStorageConfig.
    All policies are disabled by default to require admin activation.
    """
    LogRetentionPolicy = apps.get_model('log_viewer', 'LogRetentionPolicy')
    ArchiveStorageConfig = apps.get_model('log_viewer', 'ArchiveStorageConfig')
    
    # Create default retention policy for audit logs (90 days, disabled)
    LogRetentionPolicy.objects.get_or_create(
        log_type='audit',
        defaults={
            'enabled': False,
            'retention_days': 90,
            'export_before_delete': True,
            'export_format': 'csv',
            'archive_path': 'logs/archives',
        }
    )
    
    # Create default retention policy for file logs (30 days, disabled)
    LogRetentionPolicy.objects.get_or_create(
        log_type='file',
        defaults={
            'enabled': False,
            'retention_days': 30,
            'export_before_delete': True,
            'export_format': 'csv',
            'archive_path': 'logs/archives',
        }
    )
    
    # Create default archive storage configuration (10GB limit)
    ArchiveStorageConfig.objects.get_or_create(
        id=1,
        defaults={
            'max_storage_gb': 10.0,
            'warning_threshold_percent': 80,
            'critical_threshold_percent': 95,
            'current_size_gb': 0.0,
        }
    )


def reverse_default_configurations(apps, schema_editor):
    """
    Remove default configurations if migration is reversed.
    """
    LogRetentionPolicy = apps.get_model('log_viewer', 'LogRetentionPolicy')
    ArchiveStorageConfig = apps.get_model('log_viewer', 'ArchiveStorageConfig')
    
    # Delete the default retention policies
    LogRetentionPolicy.objects.filter(log_type__in=['audit', 'file']).delete()
    
    # Delete the default archive storage config
    ArchiveStorageConfig.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('log_viewer', '0002_archivestorageconfig_logcleanupschedule_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_default_configurations,
            reverse_default_configurations
        ),
    ]
