# Generated by Django 5.0.2 on 2025-11-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_scheduled',
            field=models.BooleanField(default=False, help_text='Enable automated report generation'),
        ),
        migrations.AddField(
            model_name='report',
            name='last_scheduled_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='next_scheduled_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='schedule_frequency',
            field=models.CharField(choices=[('none', 'No Automation'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='none', help_text='How often should this report be generated automatically', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('employment', 'Employment Trends'), ('geographic', 'Geographic Distribution'), ('achievements', 'Alumni Achievements'), ('feedback', 'Survey Feedback'), ('system_wide', 'System-Wide Comprehensive Report'), ('custom', 'Custom Report')], max_length=20),
        ),
    ]
