# Generated by Django 5.0.2 on 2025-11-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_report_is_scheduled_report_last_scheduled_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('employment', 'Employment Trends'), ('geographic', 'Geographic Distribution'), ('achievements', 'Alumni Achievements'), ('feedback', 'Survey Feedback'), ('donations', 'Donations Report'), ('mentors', 'Mentors Report'), ('groups', 'Groups Report'), ('custom', 'Custom Report')], max_length=20),
        ),
    ]
