# Generated by Django 4.2.27 on 2026-06-07 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_report_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('place_of_company', models.CharField(blank=True, default='', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.AddField(
            model_name='responseanswer',
            name='custom_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='scale_type',
            field=models.CharField(blank=True, choices=[('1-5', '1 to 5'), ('1-10', '1 to 10'), ('a-f', 'A to F'), ('frequency', 'Frequency (Never - Always)'), ('agreement', 'Agreement (Strongly Disagree - Strongly Agree)'), ('satisfaction', 'Satisfaction (Very Unsatisfied - Very Satisfied)'), ('extent', 'Extent of Manifestation (Very Low - Very High)'), ('custom', 'Custom Scale')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EmployerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.employer')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_responses', to='surveys.survey')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('survey', 'employer')},
            },
        ),
    ]
