# Generated by Django 4.2.27 on 2026-06-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_employer_responseanswer_custom_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerResponseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('rating_value', models.IntegerField(blank=True, null=True)),
                ('custom_text', models.CharField(blank=True, default='', max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.employerresponse')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.questionoption')),
            ],
        ),
    ]
