# Generated by Django 6.0.6 on 2026-08-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_survey_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='display_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='target_college',
            field=models.CharField(blank=True, choices=[('CAS', 'College of Arts and Sciences'), ('CBA', 'College of Business Administration'), ('CAFF', 'College of Agriculture, Forestry and Fisheries'), ('CCJE', 'College of Criminal Justice Education'), ('CEA', 'College of Engineering'), ('CIT', 'College of Industrial Technology'), ('COL', 'College of Law'), ('CNPAHS', 'College of Nursing, Pharmacy and Allied Health Sciences'), ('CTE', 'College of Education'), ('CTHM', 'College of Tourism and Hospitality Management')], default='', max_length=10),
        ),
    ]
