# Generated by Django 4.2.19 on 2025-03-12 00:10

from django.db import migrations


def create_predefined_categories(apps, schema_editor):
    Category = apps.get_model('announcements', 'Category')
    
    # Define the predefined categories with their slugs
    categories = [
        {'name': 'Campus News', 'description': 'Updates about campus activities and developments', 'slug': 'campus-news'},
        {'name': 'Events', 'description': 'Information about upcoming events and gatherings', 'slug': 'events'},
        {'name': 'Career Opportunities', 'description': 'Job postings and career advancement opportunities', 'slug': 'career-opportunities'},
        {'name': 'Alumni Spotlight', 'description': 'Highlighting achievements of alumni', 'slug': 'alumni-spotlight'},
        {'name': 'Fundraising', 'description': 'Updates on fundraising campaigns and initiatives', 'slug': 'fundraising'},
        {'name': 'Volunteer Opportunities', 'description': 'Ways to get involved and volunteer', 'slug': 'volunteer-opportunities'},
        {'name': 'Academic Updates', 'description': 'News about academic programs and achievements', 'slug': 'academic-updates'},
        {'name': 'Community Service', 'description': 'Community service initiatives and opportunities', 'slug': 'community-service'},
    ]
    
    # Create the categories if they don't already exist
    for i, category_data in enumerate(categories, 1):
        Category.objects.update_or_create(
            name=category_data['name'],
            defaults={
                'description': category_data['description'],
                'slug': category_data['slug']
            }
        )


def reverse_func(apps, schema_editor):
    # No need to delete categories when rolling back
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_predefined_categories, reverse_func),
    ]
