# Generated by Django 5.0.2 on 2025-05-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_add_predefined_categories'),
        ('announcements', '0002_create_predefined_categories'),
    ]

    operations = [
    ]
