# Generated by Django 5.0.2 on 2025-10-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnigroup',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_profiles/%Y/%m/'),
        ),
    ]
